apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorch-single-worker-distributed
spec:
  runPolicy:
    cleanPodPolicy: None  # Keep pods after completion for artifact collection
    # Add timeout protection
    activeDeadlineSeconds: 3600  # 1 hour timeout
    backoffLimit: 3              # Retry failed pods up to 3 times
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - pytorch-training-cluster-control-plane
          containers:
          - name: pytorch
            # Using custom CPU-only PyTorch image optimized for size
            image: abhijeetarundhumal/pytorch-cpu:0.0.1
            imagePullPolicy: IfNotPresent
            command:
            - python3
            - /scripts/mnist.py
            - --epochs
            - "2"
            - --save_every
            - "1"
            - --batch_size
            - "64"
            - --lr
            - "0.001"
            - --dataset_path
            - "/input"
            - --snapshot_path
            - "/output/mnist_model.pt"
            - --backend
            - "gloo"
            - --lightweight-checkpoints
            resources:
              requests:
                memory: 600Mi  # Reduced to fit worker node
                cpu: 400m
              limits:
                memory: 800Mi  # Reduced to fit worker node
                cpu: 800m
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: input
              mountPath: /input
            - name: output
              mountPath: /output
          volumes:
          - name: scripts
            hostPath:
              path: /scripts
              type: Directory
          - name: input
            hostPath:
              path: /input
              type: Directory
          - name: output
            hostPath:
              path: /output
              type: Directory
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - pytorch-training-cluster-control-plane
          containers:
          - name: pytorch
            # Using custom CPU-only PyTorch image optimized for size
            image: abhijeetarundhumal/pytorch-cpu:0.0.1
            imagePullPolicy: IfNotPresent
            command:
            - python3
            - /scripts/mnist.py
            - --epochs
            - "2"
            - --save_every
            - "1"
            - --batch_size
            - "64"
            - --lr
            - "0.001"
            - --dataset_path
            - "/input"
            - --snapshot_path
            - "/output/mnist_model.pt"
            - --backend
            - "gloo"
            - --lightweight-checkpoints
            resources:
              requests:
                memory: 600Mi  # Reduced to fit worker node
                cpu: 400m
              limits:
                memory: 800Mi  # Reduced to fit worker node
                cpu: 800m
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: input
              mountPath: /input
            - name: output
              mountPath: /output
          volumes:
          - name: scripts
            hostPath:
              path: /scripts
              type: Directory
          - name: input
            hostPath:
              path: /input
              type: Directory
          - name: output
            hostPath:
              path: /output
              type: Directory 