apiVersion: batch/v1
kind: Job
metadata:
  name: simple-mnist-training
  labels:
    app: simple-mnist-training
spec:
  template:
    spec:
      containers:
      - name: mnist-training
        image: abhijeetarundhumal/pytorch-cpu:0.0.1
        imagePullPolicy: Never
        command: ["python"]
        args: ["/workspace/scripts/mnist.py", "--epochs", "2", "--save_every", "1", "--batch_size", "64", "--lr", "0.001", "--dataset_path", "/input", "--snapshot_path", "/app/output/mnist_model.pt", "--backend", "gloo", "--lightweight-checkpoints"]
        volumeMounts:
        - name: scripts-volume
          mountPath: /workspace/scripts
        - name: output-volume
          mountPath: /app/output
        resources:
          requests:
            memory: "700Mi"
            cpu: "1000m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
      volumes:
      - name: scripts-volume
        configMap:
          name: pytorch-training-script
      - name: output-volume
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 2